version: '3.1'
services:
  frontend:
    image: bedasoftware/devdays2020-sdc-demo-frontend:latest
    ports: 
    - "5000:5000"
  backend:
    image: bedasoftware/devdays2020-sdc-demo-backend:latest
    command: ["wait-for-it.sh", "devbox:8080", "--strict", "--timeout=0", "--", "pipenv", "run", "gunicorn", "main:create_app", "--worker-class", "aiohttp.worker.GunicornWebWorker", "-b", "0.0.0.0:8081", "--reload"]
    depends_on:
      - devbox
    links:
      - devbox
    env_file:
      - .env.base
      - .env
    volumes:
      - ./config:/var/config:cached
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh:cached
    # Colored logs
    tty: true
  devbox:
    image: "healthsamurai/devbox:0.5.0-SNAPSHOT"
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8080:8080"
    env_file:
      - .env.base
      - .env
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh:cached
      - ./config:/var/config:cached
  devbox-db:
    image: "aidbox/db:11.8.6"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
